Origin alignment
aaroncherian/freemocap_validation pull request #22
Opened 2022-09-09 17:01 UTC by aaroncherian

2022-09-09 17:30 UTC, jonmatthis commented
add `__pycache` to `.gitignore`

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/COM_calculator.py
> +import numpy as np
add a `requirements.txt` file

pin all the versions with `==` based on their current status in your environment

to quote Endurance "When we update our dependencies, we want to do it on purpose"

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/COM_calculator.py
> +def calculate_segment_COM(segment_conn_len_perc_dataframe,skelcoordinates_frame_segment_joint_XYZ, num_frame_range):
use typehints when you can, and also the `-> returns` thing 

use `variable_in_question.__class__` to see the 'type'

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/COM_calculator.py
> +            this_segment_COM_percentage = segment_info['Segment COM Percentage']
try to avoid 'spaces' (whitespace) in code or code-adjacent things (like folder names, etc)

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/anthropometry_data_tables.py
> +segments = [
add a reference to where this came from

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/anthropometry_data_tables.py
> +.506, #check on the hand, did you actually use this in the com approx? Yes I did
clean it up eventually lol

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/anthropometry_data_tables.py
> +'head',
be mindful of the filename, these technically aren't "tables"

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/create_trc.py
> +    scale_factor = 0.003
should this be an input to the funtion? You can set the default value

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/create_trc.py
> +
when copy-pasting someone else's code, comment where you got it

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/create_trc.py
> +    trc_filename = 'skel_trace.trc'
file name, and file path should be input to function

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/create_trc.py
> +def flatten_mediapipe_data(skeleton_3d_data):
move this out of this file, because it's a more general purpose utility

people often have a "utilities" folder, but that's pretty generic

Don't stress too much on this for this repo, we'll figure it out in the freemocap repo

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/create_trc.py
> +def flatten_mediapipe_data(skeleton_3d_data):
also - the name implies that this is mediapipe specific, but its not

2022-09-09 17:56 UTC, jonmatthis commented on fmc_core_toolbox/freemocap_COM_runme.py
> +    skeleton_file_path = freemocap_data_array_path/'origin_aligned_Skelcoordinates_frame_segment_joint_XYZ.pkl'
doing file IO in the working function tsk tsk

2022-09-09 19:08 UTC, jonmatthis requested changes
nice stuff! Make what changes make sense and let me know when it's worth looking back at it

2022-09-09 19:08 UTC, jonmatthis commented on fmc_core_toolbox/skeleton_origin_alignment.py
> +    rotation_matrix_to_align_skeleton_with_positive_y = calculate_rotation_matrix(foot_translated_heel_unit_vector,-1*x_vector)
we'll talk about rotation later

2022-09-09 19:08 UTC, jonmatthis commented on fmc_core_toolbox/skeleton_origin_alignment.py
> +    y_aligned_skeleton_data = np.zeros(skeleton_data.shape)
make `y-align` or `z-align` a choice from the outside

2022-09-09 19:08 UTC, jonmatthis commented on fmc_core_toolbox/skeleton_origin_alignment.py
> +    if debug:
don't debug from inside the function, just `return` the data and we can plot it outside of this function

2022-09-09 19:08 UTC, jonmatthis commented on fmc_core_toolbox/time_syncing.py
> +from scipy import signal
We can also make/fix this function by way of the Trent's laser skeleton work

2022-09-14 20:34 UTC, aaroncherian commented on fmc_core_toolbox/create_trc.py
> +
put a comment giving credit to Mac in here - but I'll ask him whether he has any preferences on being probably cited here

2022-09-15 15:26 UTC, aaroncherian commented on fmc_core_toolbox/create_trc.py
> +def flatten_mediapipe_data(skeleton_3d_data):
going to table this one for the freemocap repo, since any reorganizing I do now will just have to be reorganized again for down the line

2022-11-30 17:55 UTC, merged